### ISSUE TITLE
iOS build failed

### ISSUE THREAD

**Issue by isabelleaubron** [snapcall/snapcall_react_native#18]
# Can't build iOS app

## Environment:
System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 1.18 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.3, 27.0.3, 28.0.2, 28.0.3
      System Images: android-23 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-P | Google Play Intel x86 Atom
      Android NDK: 21.0.6113669
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-git-upgrade: 0.2.7

## Steps To Reproduce

1. yarn add react-native-snapcall
2. cd ios && pod install
3. build iOS app in XCode

iOS build failed with errors in files RNSnapcallEventListener.h and RNSnapcallReact.h ("Expected a type", "No type or protocol named 'objc_SCClientListener'")

I've tried to add header path as indicated in documentation but same errors.

<img width="1177" alt="Capture d’écran 2020-01-27 à 15 14 22" src="https://user-images.githubusercontent.com/13640590/73181559-b847fc00-4117-11ea-9afc-f6765b7c5d17.png">

**Comment by pnoyelle** [comment]
Hello, thanks for the report. 
I check that in the day.

**Comment by pnoyelle** [comment]
Apple changed some build part. When using Swift from objective-c i need to import Snapcall_Framework-Swift.h, the one actually distributed add the define only for the arm arch and not for X86_64 for the simulator due to recent apple change (#elif defined(__arm64__) && __arm64__ in the header).

This will be resolved in the 2.0.1 release, and you will be able to compile our library for the simulator.
